simulates delay
JustinObanor/lets_Go pull request #11
Opened 2020-03-31 06:37 UTC by JustinObanor

2020-03-31 06:40 UTC, JustinObanor commented on kufar/widget/main.go
>  			c <- widget{label: "widget_" + strconv.Itoa(num), time: time.Now()}
not sure if i need this line still

2020-04-02 07:20 UTC, bynov requested changes
You should create two separate wgs. One for producer and second for consumers. When all consumers will exit from loop, you should call `wg.Done()`.
And in main func you should stop your program when `wg.Wait()` for consumer wg's.

2020-04-02 07:20 UTC, bynov commented on kufar/widget/main.go
> +var con = flag.Int("c", 1, "widgets consumed")
It's number of consumers :P

2020-04-02 07:20 UTC, bynov commented on kufar/widget/main.go
> +func consumer(ctx context.Context, c chan widget, wg *sync.WaitGroup, con int) {
You don't need a context here and a select

2020-04-03 09:01 UTC, bynov approved these changes

2020-04-03 09:01 UTC, bynov commented on kufar/widget/main.go
> +	go func() {
Please remove that go func.

IN your main func it need to be `close(c)` and after that `cwg.Wait` to wait until all consumers will finish with processing

2020-04-03 09:25 UTC, merged